Clear Maven local repository during nuke
rock3r/deep-clean pull request #9
Opened 2021-05-16 09:31 UTC by IslamSalah

## What is the aim of this PR?

Recently I have been facing an issue on building a project on my machine. The issue couldn't be reproduced on CI machines or my personal machine. It turned out after a deeper investigation to be a single corrupted artefact in the Maven local  repository which is part of the machine global cache

## Implemented solution

As a part of global cache invalidation, aka nuke, the proposed change locates and clears the global [Maven cache directory](https://www.baeldung.com/maven-local-repository)
```bash
~/.m2        # dir on mac
```

## REQUIRED: pre-PR checklist

* [x] The project compiles/runs
* [x] The implemented solution works as intended
* [x] Dry-run (`-d`) doesn't actually perform any action besides logging
* [x] The `README.md` file has been updated

2021-05-17 07:13 UTC, rock3r requested changes
Thanks for the contribution! Good idea :) Just a couple of minor tweaks and it's good to go for me.

By the way, can you update the usage instructions in the [README](https://github.com/rock3r/deep-clean#running-the-script)?

2021-05-17 07:13 UTC, rock3r commented on deep-clean.kts
> +}
```suggestion
fun locateMavenLocalRepository(): File? =
    File(userHome, ".m2"),takeIf { it.exists() }
}
```

2021-05-17 07:13 UTC, rock3r commented on deep-clean.kts
> +    if(mavenLocalRepository != null) {
```suggestion
    if (mavenLocalRepository != null) {
```

2021-05-17 13:32 UTC, IslamSalah commented
@rock3r Thanks for taking the time to review. I'm not sure what else should be in the README file?
Current change: https://github.com/rock3r/deep-clean/pull/9/commits/7ca55fcf83bb612b4bde4a1b0f05a62f8780196d

2021-05-17 14:00 UTC, rock3r commented
> I'm not sure what else should be in the README file?

Just make sure it's up to date with the change you've made to the usages message :)

https://github.com/rock3r/deep-clean/pull/9/files#diff-fd5d67ef3c63d130f463aaa1a1131394f21e2148a91e21ecc28fd1096c259dfeR41

2021-05-17 16:12 UTC, IslamSalah commented
Thanks for still being here, I assumed the README update I have made before opening the PR reflects the code change, Otherwise can you list the change you'd like to have?

2021-05-17 16:33 UTC, rock3r commented
Essentially, you need to make the same change you've made in the script (`deep-clean.kts`) and that I've linked, in the `README` too.

2021-05-17 17:01 UTC, IslamSalah commented
Oh! it was localy done but not pushed. Even the commit message was like `Update README file`. Now it should be there

2021-05-18 09:00 UTC, rock3r approved these changes
Thanks! 🙌

2021-05-18 09:00 UTC, merged